################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
CPP_UPPER_SRCS := 
C++M_SRCS := 
C++_UPPER_SRCS := 
CC_UPPER_SRCS := 
CPP_SRCS := 
O_SRCS := 
ELF_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
CCM_UPPER_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
CXXM_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
CXX_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
CC_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C++M_UPPER_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CC_UPPER_DEPS := 
C++M_UPPER_DEPS := 
C++_UPPER_DEPS := 
CPP_UPPER_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
CXXM_DEPS := 
JMP_UPPER_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
CXX_DEPS := 
SREC := 
JMP_DEPS := 
CXX_UPPER_DEPS := 
CCM_DEPS := 
P_UPPER_DEPS := 
CXXM_UPPER_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
CCM_UPPER_DEPS := 
SRC_DEPS := 
PP_DEPS := 
CC_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
S_UPPER_DEPS := 
MAP := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Application \
Application/images \
mtk3_bsp2/mtkernel/device/adc \
mtk3_bsp2/mtkernel/device/adc/sysdepend/rx231 \
mtk3_bsp2/mtkernel/device/adc/sysdepend/rx65n \
mtk3_bsp2/mtkernel/device/adc/sysdepend/rza2m \
mtk3_bsp2/mtkernel/device/adc/sysdepend/stm32h7 \
mtk3_bsp2/mtkernel/device/adc/sysdepend/stm32l4 \
mtk3_bsp2/mtkernel/device/adc/sysdepend/tx03_m367 \
mtk3_bsp2/mtkernel/device/common/drvif \
mtk3_bsp2/mtkernel/device/i2c \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/rx231 \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/rx65n \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/rza2m \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/stm32h7 \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/stm32l4 \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/tx03_m367 \
mtk3_bsp2/mtkernel/device/ser \
mtk3_bsp2/mtkernel/device/ser/sysdepend/rx231 \
mtk3_bsp2/mtkernel/device/ser/sysdepend/rx65n \
mtk3_bsp2/mtkernel/device/ser/sysdepend/rza2m \
mtk3_bsp2/mtkernel/device/ser/sysdepend/stm32h7 \
mtk3_bsp2/mtkernel/device/ser/sysdepend/stm32l4 \
mtk3_bsp2/mtkernel/device/ser/sysdepend/tx03_m367 \
mtk3_bsp2/mtkernel/etc/linker/iote_m367 \
mtk3_bsp2/mtkernel/etc/linker/iote_rx231 \
mtk3_bsp2/mtkernel/etc/linker/iote_rza2m \
mtk3_bsp2/mtkernel/etc/linker/iote_stm32l4 \
mtk3_bsp2/mtkernel/kernel/inittask \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/core/armv7a \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/core/armv7m \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/core/rxv2 \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/rx231 \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/rx65n \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/rza2m \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/stm32h7 \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/stm32l4 \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/tx03_m367 \
mtk3_bsp2/mtkernel/kernel/sysdepend/iote_m367 \
mtk3_bsp2/mtkernel/kernel/sysdepend/iote_rx231 \
mtk3_bsp2/mtkernel/kernel/sysdepend/iote_rza2m \
mtk3_bsp2/mtkernel/kernel/sysdepend/iote_stm32l4 \
mtk3_bsp2/mtkernel/kernel/sysinit \
mtk3_bsp2/mtkernel/kernel/tkernel \
mtk3_bsp2/mtkernel/kernel/tstdlib \
mtk3_bsp2/mtkernel/kernel/usermain \
mtk3_bsp2/mtkernel/lib/libtk \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/core/armv7a \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/core/armv7m \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/core/rxv2 \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/rx231 \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/rx65n \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/rza2m \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/stm32h7 \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/stm32l4 \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/tx03_m367 \
mtk3_bsp2/mtkernel/lib/libtm \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/iote_m367 \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/iote_rx231 \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/iote_rza2m \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/iote_stm32l4 \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/no_device \
mtk3_bsp2/sysdepend/nxp_mcux/cpu/core/armv8m \
mtk3_bsp2/sysdepend/nxp_mcux/device/hal_adc \
mtk3_bsp2/sysdepend/nxp_mcux/device/hal_lpi2c \
mtk3_bsp2/sysdepend/nxp_mcux \
mtk3_bsp2/sysdepend/nxp_mcux/lib/libtk/cpu/core/armv8m \
mtk3_bsp2/sysdepend/nxp_mcux/lib/libtm/evk_lpc55s69 \
mtk3_bsp2/sysdepend/nxp_mcux/lib/libtm/frdm_mcxn947 \
mtk3_bsp2/sysdepend/ra_fsp/cpu/core/armv7m \
mtk3_bsp2/sysdepend/ra_fsp/cpu/core/armv8m \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_adc \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_i2c \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_i3c_i2c \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_sci_i2c \
mtk3_bsp2/sysdepend/ra_fsp \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtk/cpu/core/armv7m \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtk/cpu/core/armv8m \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/arduino_unor4 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/clicker_ra4m1 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/ek_ra6m3 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/ek_ra8d1 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/ek_ra8m1 \
mtk3_bsp2/sysdepend/stm32_cube/cpu/core/armv7m \
mtk3_bsp2/sysdepend/stm32_cube/cpu/core/armv8m \
mtk3_bsp2/sysdepend/stm32_cube/device/hal_adc \
mtk3_bsp2/sysdepend/stm32_cube/device/hal_adc/sysdepend \
mtk3_bsp2/sysdepend/stm32_cube/device/hal_i2c \
mtk3_bsp2/sysdepend/stm32_cube \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/core/armv7m \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/core/armv8m \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32f4 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32f7 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32g4 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32h7 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32l4 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32n6 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/discovery_stm32n657 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32f401 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32f411 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32f446 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32f767 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32g431 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32g491 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32h723 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32l476 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32l4r5 \
mtk3_bsp2/sysdepend/xmc_mtb/cpu/core/armv7m \
mtk3_bsp2/sysdepend/xmc_mtb/cpu/xmc7200 \
mtk3_bsp2/sysdepend/xmc_mtb/device/hal_adc \
mtk3_bsp2/sysdepend/xmc_mtb/device/hal_adc/sysdepend/xmc7200 \
mtk3_bsp2/sysdepend/xmc_mtb/device/hal_i2c \
mtk3_bsp2/sysdepend/xmc_mtb/device/hal_i2c/sysdepend/xmc7200 \
mtk3_bsp2/sysdepend/xmc_mtb \
mtk3_bsp2/sysdepend/xmc_mtb/lib/libtk/cpu/core/armv7m \
mtk3_bsp2/sysdepend/xmc_mtb/lib/libtk/cpu/xmc7200 \
mtk3_bsp2/sysdepend/xmc_mtb/lib/libtm/evk_xmc7200 \
ra/board/ra8d1_ek \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/r_dtc \
ra/fsp/src/r_glcdc \
ra/fsp/src/r_gpt \
ra/fsp/src/r_icu \
ra/fsp/src/r_iic_master \
ra/fsp/src/r_ioport \
ra/fsp/src/r_mipi_dsi \
ra/fsp/src/r_mipi_phy \
ra/fsp/src/r_sci_b_uart \
ra/fsp/src/r_ssi \
ra_gen \
src/SEGGER_RTT \
src \
tflm \
tflm/signal/micro/kernels \
tflm/signal/src \
tflm/signal/src/kiss_fft_wrappers \
tflm/tensorflow/compiler/mlir/lite/core/api \
tflm/tensorflow/compiler/mlir/lite/schema \
tflm/tensorflow/lite \
tflm/tensorflow/lite/core/api \
tflm/tensorflow/lite/core/c \
tflm/tensorflow/lite/kernels/internal \
tflm/tensorflow/lite/kernels/internal/reference \
tflm/tensorflow/lite/kernels \
tflm/tensorflow/lite/micro \
tflm/tensorflow/lite/micro/arena_allocator \
tflm/tensorflow/lite/micro/kernels \
tflm/tensorflow/lite/micro/kernels/cmsis_nn \
tflm/tensorflow/lite/micro/memory_planner \
tflm/tensorflow/lite/micro/tflite_bridge \
tflm/third_party/cmsis_nn/Source/ActivationFunctions \
tflm/third_party/cmsis_nn/Source/BasicMathFunctions \
tflm/third_party/cmsis_nn/Source/ConcatenationFunctions \
tflm/third_party/cmsis_nn/Source/ConvolutionFunctions \
tflm/third_party/cmsis_nn/Source/FullyConnectedFunctions \
tflm/third_party/cmsis_nn/Source/LSTMFunctions \
tflm/third_party/cmsis_nn/Source/NNSupportFunctions \
tflm/third_party/cmsis_nn/Source/PadFunctions \
tflm/third_party/cmsis_nn/Source/PoolingFunctions \
tflm/third_party/cmsis_nn/Source/ReshapeFunctions \
tflm/third_party/cmsis_nn/Source/SVDFunctions \
tflm/third_party/cmsis_nn/Source/SoftmaxFunctions \
tflm/third_party/cmsis_nn/Source/TransposeFunctions \
tflm/third_party/flatbuffers/include/flatbuffers \
tflm/third_party/kissfft \

