################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../tflm/tensorflow/lite/micro/kernels/activations.cc \
../tflm/tensorflow/lite/micro/kernels/activations_common.cc \
../tflm/tensorflow/lite/micro/kernels/add_common.cc \
../tflm/tensorflow/lite/micro/kernels/add_n.cc \
../tflm/tensorflow/lite/micro/kernels/arg_min_max.cc \
../tflm/tensorflow/lite/micro/kernels/assign_variable.cc \
../tflm/tensorflow/lite/micro/kernels/batch_matmul_common.cc \
../tflm/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../tflm/tensorflow/lite/micro/kernels/broadcast_args.cc \
../tflm/tensorflow/lite/micro/kernels/broadcast_to.cc \
../tflm/tensorflow/lite/micro/kernels/call_once.cc \
../tflm/tensorflow/lite/micro/kernels/cast.cc \
../tflm/tensorflow/lite/micro/kernels/ceil.cc \
../tflm/tensorflow/lite/micro/kernels/circular_buffer.cc \
../tflm/tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../tflm/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.cc \
../tflm/tensorflow/lite/micro/kernels/comparisons.cc \
../tflm/tensorflow/lite/micro/kernels/concatenation.cc \
../tflm/tensorflow/lite/micro/kernels/conv_common.cc \
../tflm/tensorflow/lite/micro/kernels/cumsum.cc \
../tflm/tensorflow/lite/micro/kernels/decompress.cc \
../tflm/tensorflow/lite/micro/kernels/decompress_common.cc \
../tflm/tensorflow/lite/micro/kernels/depth_to_space.cc \
../tflm/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../tflm/tensorflow/lite/micro/kernels/dequantize.cc \
../tflm/tensorflow/lite/micro/kernels/dequantize_common.cc \
../tflm/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../tflm/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.cc \
../tflm/tensorflow/lite/micro/kernels/div.cc \
../tflm/tensorflow/lite/micro/kernels/elementwise.cc \
../tflm/tensorflow/lite/micro/kernels/elu.cc \
../tflm/tensorflow/lite/micro/kernels/embedding_lookup.cc \
../tflm/tensorflow/lite/micro/kernels/energy.cc \
../tflm/tensorflow/lite/micro/kernels/ethosu.cc \
../tflm/tensorflow/lite/micro/kernels/exp.cc \
../tflm/tensorflow/lite/micro/kernels/expand_dims.cc \
../tflm/tensorflow/lite/micro/kernels/fft_auto_scale_common.cc \
../tflm/tensorflow/lite/micro/kernels/fft_auto_scale_kernel.cc \
../tflm/tensorflow/lite/micro/kernels/fill.cc \
../tflm/tensorflow/lite/micro/kernels/filter_bank.cc \
../tflm/tensorflow/lite/micro/kernels/filter_bank_log.cc \
../tflm/tensorflow/lite/micro/kernels/filter_bank_spectral_subtraction.cc \
../tflm/tensorflow/lite/micro/kernels/filter_bank_square_root.cc \
../tflm/tensorflow/lite/micro/kernels/filter_bank_square_root_common.cc \
../tflm/tensorflow/lite/micro/kernels/floor.cc \
../tflm/tensorflow/lite/micro/kernels/floor_div.cc \
../tflm/tensorflow/lite/micro/kernels/floor_mod.cc \
../tflm/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../tflm/tensorflow/lite/micro/kernels/gather.cc \
../tflm/tensorflow/lite/micro/kernels/gather_nd.cc \
../tflm/tensorflow/lite/micro/kernels/hard_swish.cc \
../tflm/tensorflow/lite/micro/kernels/hard_swish_common.cc \
../tflm/tensorflow/lite/micro/kernels/if.cc \
../tflm/tensorflow/lite/micro/kernels/kernel_runner.cc \
../tflm/tensorflow/lite/micro/kernels/kernel_util.cc \
../tflm/tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../tflm/tensorflow/lite/micro/kernels/l2norm.cc \
../tflm/tensorflow/lite/micro/kernels/leaky_relu.cc \
../tflm/tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../tflm/tensorflow/lite/micro/kernels/log_softmax.cc \
../tflm/tensorflow/lite/micro/kernels/logical.cc \
../tflm/tensorflow/lite/micro/kernels/logical_common.cc \
../tflm/tensorflow/lite/micro/kernels/logistic.cc \
../tflm/tensorflow/lite/micro/kernels/logistic_common.cc \
../tflm/tensorflow/lite/micro/kernels/lstm_eval.cc \
../tflm/tensorflow/lite/micro/kernels/lstm_eval_common.cc \
../tflm/tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../tflm/tensorflow/lite/micro/kernels/mirror_pad.cc \
../tflm/tensorflow/lite/micro/kernels/mul_common.cc \
../tflm/tensorflow/lite/micro/kernels/neg.cc \
../tflm/tensorflow/lite/micro/kernels/pack.cc \
../tflm/tensorflow/lite/micro/kernels/pad_common.cc \
../tflm/tensorflow/lite/micro/kernels/pcan.cc \
../tflm/tensorflow/lite/micro/kernels/pooling_common.cc \
../tflm/tensorflow/lite/micro/kernels/prelu.cc \
../tflm/tensorflow/lite/micro/kernels/prelu_common.cc \
../tflm/tensorflow/lite/micro/kernels/quantize.cc \
../tflm/tensorflow/lite/micro/kernels/quantize_common.cc \
../tflm/tensorflow/lite/micro/kernels/read_variable.cc \
../tflm/tensorflow/lite/micro/kernels/reduce.cc \
../tflm/tensorflow/lite/micro/kernels/reduce_common.cc \
../tflm/tensorflow/lite/micro/kernels/reshape.cc \
../tflm/tensorflow/lite/micro/kernels/reshape_common.cc \
../tflm/tensorflow/lite/micro/kernels/resize_bilinear.cc \
../tflm/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../tflm/tensorflow/lite/micro/kernels/reverse.cc \
../tflm/tensorflow/lite/micro/kernels/round.cc \
../tflm/tensorflow/lite/micro/kernels/select.cc \
../tflm/tensorflow/lite/micro/kernels/shape.cc \
../tflm/tensorflow/lite/micro/kernels/slice.cc \
../tflm/tensorflow/lite/micro/kernels/softmax_common.cc \
../tflm/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../tflm/tensorflow/lite/micro/kernels/space_to_depth.cc \
../tflm/tensorflow/lite/micro/kernels/split.cc \
../tflm/tensorflow/lite/micro/kernels/split_v.cc \
../tflm/tensorflow/lite/micro/kernels/squared_difference.cc \
../tflm/tensorflow/lite/micro/kernels/squeeze.cc \
../tflm/tensorflow/lite/micro/kernels/strided_slice.cc \
../tflm/tensorflow/lite/micro/kernels/strided_slice_common.cc \
../tflm/tensorflow/lite/micro/kernels/sub.cc \
../tflm/tensorflow/lite/micro/kernels/sub_common.cc \
../tflm/tensorflow/lite/micro/kernels/svdf_common.cc \
../tflm/tensorflow/lite/micro/kernels/tanh.cc \
../tflm/tensorflow/lite/micro/kernels/transpose_common.cc \
../tflm/tensorflow/lite/micro/kernels/unpack.cc \
../tflm/tensorflow/lite/micro/kernels/var_handle.cc \
../tflm/tensorflow/lite/micro/kernels/while.cc \
../tflm/tensorflow/lite/micro/kernels/window.cc \
../tflm/tensorflow/lite/micro/kernels/zeros_like.cc 

SREC += \
tc25_v1_0D.srec 

CC_DEPS += \
./tflm/tensorflow/lite/micro/kernels/activations.d \
./tflm/tensorflow/lite/micro/kernels/activations_common.d \
./tflm/tensorflow/lite/micro/kernels/add_common.d \
./tflm/tensorflow/lite/micro/kernels/add_n.d \
./tflm/tensorflow/lite/micro/kernels/arg_min_max.d \
./tflm/tensorflow/lite/micro/kernels/assign_variable.d \
./tflm/tensorflow/lite/micro/kernels/batch_matmul_common.d \
./tflm/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./tflm/tensorflow/lite/micro/kernels/broadcast_args.d \
./tflm/tensorflow/lite/micro/kernels/broadcast_to.d \
./tflm/tensorflow/lite/micro/kernels/call_once.d \
./tflm/tensorflow/lite/micro/kernels/cast.d \
./tflm/tensorflow/lite/micro/kernels/ceil.d \
./tflm/tensorflow/lite/micro/kernels/circular_buffer.d \
./tflm/tensorflow/lite/micro/kernels/circular_buffer_common.d \
./tflm/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.d \
./tflm/tensorflow/lite/micro/kernels/comparisons.d \
./tflm/tensorflow/lite/micro/kernels/concatenation.d \
./tflm/tensorflow/lite/micro/kernels/conv_common.d \
./tflm/tensorflow/lite/micro/kernels/cumsum.d \
./tflm/tensorflow/lite/micro/kernels/decompress.d \
./tflm/tensorflow/lite/micro/kernels/decompress_common.d \
./tflm/tensorflow/lite/micro/kernels/depth_to_space.d \
./tflm/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./tflm/tensorflow/lite/micro/kernels/dequantize.d \
./tflm/tensorflow/lite/micro/kernels/dequantize_common.d \
./tflm/tensorflow/lite/micro/kernels/detection_postprocess.d \
./tflm/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.d \
./tflm/tensorflow/lite/micro/kernels/div.d \
./tflm/tensorflow/lite/micro/kernels/elementwise.d \
./tflm/tensorflow/lite/micro/kernels/elu.d \
./tflm/tensorflow/lite/micro/kernels/embedding_lookup.d \
./tflm/tensorflow/lite/micro/kernels/energy.d \
./tflm/tensorflow/lite/micro/kernels/ethosu.d \
./tflm/tensorflow/lite/micro/kernels/exp.d \
./tflm/tensorflow/lite/micro/kernels/expand_dims.d \
./tflm/tensorflow/lite/micro/kernels/fft_auto_scale_common.d \
./tflm/tensorflow/lite/micro/kernels/fft_auto_scale_kernel.d \
./tflm/tensorflow/lite/micro/kernels/fill.d \
./tflm/tensorflow/lite/micro/kernels/filter_bank.d \
./tflm/tensorflow/lite/micro/kernels/filter_bank_log.d \
./tflm/tensorflow/lite/micro/kernels/filter_bank_spectral_subtraction.d \
./tflm/tensorflow/lite/micro/kernels/filter_bank_square_root.d \
./tflm/tensorflow/lite/micro/kernels/filter_bank_square_root_common.d \
./tflm/tensorflow/lite/micro/kernels/floor.d \
./tflm/tensorflow/lite/micro/kernels/floor_div.d \
./tflm/tensorflow/lite/micro/kernels/floor_mod.d \
./tflm/tensorflow/lite/micro/kernels/fully_connected_common.d \
./tflm/tensorflow/lite/micro/kernels/gather.d \
./tflm/tensorflow/lite/micro/kernels/gather_nd.d \
./tflm/tensorflow/lite/micro/kernels/hard_swish.d \
./tflm/tensorflow/lite/micro/kernels/hard_swish_common.d \
./tflm/tensorflow/lite/micro/kernels/if.d \
./tflm/tensorflow/lite/micro/kernels/kernel_runner.d \
./tflm/tensorflow/lite/micro/kernels/kernel_util.d \
./tflm/tensorflow/lite/micro/kernels/l2_pool_2d.d \
./tflm/tensorflow/lite/micro/kernels/l2norm.d \
./tflm/tensorflow/lite/micro/kernels/leaky_relu.d \
./tflm/tensorflow/lite/micro/kernels/leaky_relu_common.d \
./tflm/tensorflow/lite/micro/kernels/log_softmax.d \
./tflm/tensorflow/lite/micro/kernels/logical.d \
./tflm/tensorflow/lite/micro/kernels/logical_common.d \
./tflm/tensorflow/lite/micro/kernels/logistic.d \
./tflm/tensorflow/lite/micro/kernels/logistic_common.d \
./tflm/tensorflow/lite/micro/kernels/lstm_eval.d \
./tflm/tensorflow/lite/micro/kernels/lstm_eval_common.d \
./tflm/tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./tflm/tensorflow/lite/micro/kernels/mirror_pad.d \
./tflm/tensorflow/lite/micro/kernels/mul_common.d \
./tflm/tensorflow/lite/micro/kernels/neg.d \
./tflm/tensorflow/lite/micro/kernels/pack.d \
./tflm/tensorflow/lite/micro/kernels/pad_common.d \
./tflm/tensorflow/lite/micro/kernels/pcan.d \
./tflm/tensorflow/lite/micro/kernels/pooling_common.d \
./tflm/tensorflow/lite/micro/kernels/prelu.d \
./tflm/tensorflow/lite/micro/kernels/prelu_common.d \
./tflm/tensorflow/lite/micro/kernels/quantize.d \
./tflm/tensorflow/lite/micro/kernels/quantize_common.d \
./tflm/tensorflow/lite/micro/kernels/read_variable.d \
./tflm/tensorflow/lite/micro/kernels/reduce.d \
./tflm/tensorflow/lite/micro/kernels/reduce_common.d \
./tflm/tensorflow/lite/micro/kernels/reshape.d \
./tflm/tensorflow/lite/micro/kernels/reshape_common.d \
./tflm/tensorflow/lite/micro/kernels/resize_bilinear.d \
./tflm/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./tflm/tensorflow/lite/micro/kernels/reverse.d \
./tflm/tensorflow/lite/micro/kernels/round.d \
./tflm/tensorflow/lite/micro/kernels/select.d \
./tflm/tensorflow/lite/micro/kernels/shape.d \
./tflm/tensorflow/lite/micro/kernels/slice.d \
./tflm/tensorflow/lite/micro/kernels/softmax_common.d \
./tflm/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./tflm/tensorflow/lite/micro/kernels/space_to_depth.d \
./tflm/tensorflow/lite/micro/kernels/split.d \
./tflm/tensorflow/lite/micro/kernels/split_v.d \
./tflm/tensorflow/lite/micro/kernels/squared_difference.d \
./tflm/tensorflow/lite/micro/kernels/squeeze.d \
./tflm/tensorflow/lite/micro/kernels/strided_slice.d \
./tflm/tensorflow/lite/micro/kernels/strided_slice_common.d \
./tflm/tensorflow/lite/micro/kernels/sub.d \
./tflm/tensorflow/lite/micro/kernels/sub_common.d \
./tflm/tensorflow/lite/micro/kernels/svdf_common.d \
./tflm/tensorflow/lite/micro/kernels/tanh.d \
./tflm/tensorflow/lite/micro/kernels/transpose_common.d \
./tflm/tensorflow/lite/micro/kernels/unpack.d \
./tflm/tensorflow/lite/micro/kernels/var_handle.d \
./tflm/tensorflow/lite/micro/kernels/while.d \
./tflm/tensorflow/lite/micro/kernels/window.d \
./tflm/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./tflm/tensorflow/lite/micro/kernels/activations.o \
./tflm/tensorflow/lite/micro/kernels/activations_common.o \
./tflm/tensorflow/lite/micro/kernels/add_common.o \
./tflm/tensorflow/lite/micro/kernels/add_n.o \
./tflm/tensorflow/lite/micro/kernels/arg_min_max.o \
./tflm/tensorflow/lite/micro/kernels/assign_variable.o \
./tflm/tensorflow/lite/micro/kernels/batch_matmul_common.o \
./tflm/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./tflm/tensorflow/lite/micro/kernels/broadcast_args.o \
./tflm/tensorflow/lite/micro/kernels/broadcast_to.o \
./tflm/tensorflow/lite/micro/kernels/call_once.o \
./tflm/tensorflow/lite/micro/kernels/cast.o \
./tflm/tensorflow/lite/micro/kernels/ceil.o \
./tflm/tensorflow/lite/micro/kernels/circular_buffer.o \
./tflm/tensorflow/lite/micro/kernels/circular_buffer_common.o \
./tflm/tensorflow/lite/micro/kernels/circular_buffer_flexbuffers_generated_data.o \
./tflm/tensorflow/lite/micro/kernels/comparisons.o \
./tflm/tensorflow/lite/micro/kernels/concatenation.o \
./tflm/tensorflow/lite/micro/kernels/conv_common.o \
./tflm/tensorflow/lite/micro/kernels/cumsum.o \
./tflm/tensorflow/lite/micro/kernels/decompress.o \
./tflm/tensorflow/lite/micro/kernels/decompress_common.o \
./tflm/tensorflow/lite/micro/kernels/depth_to_space.o \
./tflm/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./tflm/tensorflow/lite/micro/kernels/dequantize.o \
./tflm/tensorflow/lite/micro/kernels/dequantize_common.o \
./tflm/tensorflow/lite/micro/kernels/detection_postprocess.o \
./tflm/tensorflow/lite/micro/kernels/detection_postprocess_flexbuffers_generated_data.o \
./tflm/tensorflow/lite/micro/kernels/div.o \
./tflm/tensorflow/lite/micro/kernels/elementwise.o \
./tflm/tensorflow/lite/micro/kernels/elu.o \
./tflm/tensorflow/lite/micro/kernels/embedding_lookup.o \
./tflm/tensorflow/lite/micro/kernels/energy.o \
./tflm/tensorflow/lite/micro/kernels/ethosu.o \
./tflm/tensorflow/lite/micro/kernels/exp.o \
./tflm/tensorflow/lite/micro/kernels/expand_dims.o \
./tflm/tensorflow/lite/micro/kernels/fft_auto_scale_common.o \
./tflm/tensorflow/lite/micro/kernels/fft_auto_scale_kernel.o \
./tflm/tensorflow/lite/micro/kernels/fill.o \
./tflm/tensorflow/lite/micro/kernels/filter_bank.o \
./tflm/tensorflow/lite/micro/kernels/filter_bank_log.o \
./tflm/tensorflow/lite/micro/kernels/filter_bank_spectral_subtraction.o \
./tflm/tensorflow/lite/micro/kernels/filter_bank_square_root.o \
./tflm/tensorflow/lite/micro/kernels/filter_bank_square_root_common.o \
./tflm/tensorflow/lite/micro/kernels/floor.o \
./tflm/tensorflow/lite/micro/kernels/floor_div.o \
./tflm/tensorflow/lite/micro/kernels/floor_mod.o \
./tflm/tensorflow/lite/micro/kernels/fully_connected_common.o \
./tflm/tensorflow/lite/micro/kernels/gather.o \
./tflm/tensorflow/lite/micro/kernels/gather_nd.o \
./tflm/tensorflow/lite/micro/kernels/hard_swish.o \
./tflm/tensorflow/lite/micro/kernels/hard_swish_common.o \
./tflm/tensorflow/lite/micro/kernels/if.o \
./tflm/tensorflow/lite/micro/kernels/kernel_runner.o \
./tflm/tensorflow/lite/micro/kernels/kernel_util.o \
./tflm/tensorflow/lite/micro/kernels/l2_pool_2d.o \
./tflm/tensorflow/lite/micro/kernels/l2norm.o \
./tflm/tensorflow/lite/micro/kernels/leaky_relu.o \
./tflm/tensorflow/lite/micro/kernels/leaky_relu_common.o \
./tflm/tensorflow/lite/micro/kernels/log_softmax.o \
./tflm/tensorflow/lite/micro/kernels/logical.o \
./tflm/tensorflow/lite/micro/kernels/logical_common.o \
./tflm/tensorflow/lite/micro/kernels/logistic.o \
./tflm/tensorflow/lite/micro/kernels/logistic_common.o \
./tflm/tensorflow/lite/micro/kernels/lstm_eval.o \
./tflm/tensorflow/lite/micro/kernels/lstm_eval_common.o \
./tflm/tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./tflm/tensorflow/lite/micro/kernels/mirror_pad.o \
./tflm/tensorflow/lite/micro/kernels/mul_common.o \
./tflm/tensorflow/lite/micro/kernels/neg.o \
./tflm/tensorflow/lite/micro/kernels/pack.o \
./tflm/tensorflow/lite/micro/kernels/pad_common.o \
./tflm/tensorflow/lite/micro/kernels/pcan.o \
./tflm/tensorflow/lite/micro/kernels/pooling_common.o \
./tflm/tensorflow/lite/micro/kernels/prelu.o \
./tflm/tensorflow/lite/micro/kernels/prelu_common.o \
./tflm/tensorflow/lite/micro/kernels/quantize.o \
./tflm/tensorflow/lite/micro/kernels/quantize_common.o \
./tflm/tensorflow/lite/micro/kernels/read_variable.o \
./tflm/tensorflow/lite/micro/kernels/reduce.o \
./tflm/tensorflow/lite/micro/kernels/reduce_common.o \
./tflm/tensorflow/lite/micro/kernels/reshape.o \
./tflm/tensorflow/lite/micro/kernels/reshape_common.o \
./tflm/tensorflow/lite/micro/kernels/resize_bilinear.o \
./tflm/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./tflm/tensorflow/lite/micro/kernels/reverse.o \
./tflm/tensorflow/lite/micro/kernels/round.o \
./tflm/tensorflow/lite/micro/kernels/select.o \
./tflm/tensorflow/lite/micro/kernels/shape.o \
./tflm/tensorflow/lite/micro/kernels/slice.o \
./tflm/tensorflow/lite/micro/kernels/softmax_common.o \
./tflm/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./tflm/tensorflow/lite/micro/kernels/space_to_depth.o \
./tflm/tensorflow/lite/micro/kernels/split.o \
./tflm/tensorflow/lite/micro/kernels/split_v.o \
./tflm/tensorflow/lite/micro/kernels/squared_difference.o \
./tflm/tensorflow/lite/micro/kernels/squeeze.o \
./tflm/tensorflow/lite/micro/kernels/strided_slice.o \
./tflm/tensorflow/lite/micro/kernels/strided_slice_common.o \
./tflm/tensorflow/lite/micro/kernels/sub.o \
./tflm/tensorflow/lite/micro/kernels/sub_common.o \
./tflm/tensorflow/lite/micro/kernels/svdf_common.o \
./tflm/tensorflow/lite/micro/kernels/tanh.o \
./tflm/tensorflow/lite/micro/kernels/transpose_common.o \
./tflm/tensorflow/lite/micro/kernels/unpack.o \
./tflm/tensorflow/lite/micro/kernels/var_handle.o \
./tflm/tensorflow/lite/micro/kernels/while.o \
./tflm/tensorflow/lite/micro/kernels/window.o \
./tflm/tensorflow/lite/micro/kernels/zeros_like.o 

MAP += \
tc25_v1_0D.map 


# Each subdirectory must supply rules for building sources it contributes
tflm/tensorflow/lite/micro/kernels/%.o: ../tflm/tensorflow/lite/micro/kernels/%.cc
	$(file > $@.in,-mthumb -mfloat-abi=hard -march=armv8.1-m.main+mve.fp+fp.dp -O2 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall -g -gdwarf-4 -D_RA_CORE=CM85 -D_RA_ORDINAL=1 -D_RAFSP_EK_RA8D1_ -D_RENESAS_RA_ -DFIXED_POINT=16 -DCMSIS_NN -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/ra/arm/CMSIS_6/CMSIS/Core/Include" -I"." -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/src" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/ra/fsp/inc" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/ra/fsp/inc/api" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/ra/fsp/inc/instances" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/ra_gen" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/ra_cfg/fsp_cfg/bsp" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/ra_cfg/fsp_cfg" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/mtk3_bsp2" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/mtk3_bsp2/config" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/mtk3_bsp2/config/config_bsp" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/mtk3_bsp2/include" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/mtk3_bsp2/mtkernel/include" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/Application/include" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/tflm/third_party" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/tflm/tensorflow" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/tflm" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/tflm/third_party/gemmlowp" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/tflm/third_party/gemmlowp/fixedpoint" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/script" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/tflm/tensorflow/lite/micro/kernels" -I"C:/Users/tsuto/e2_studio/workspace/tc25_v1_0D/tflm/third_party/cmsis_nn/Include" -std=c++14 -fabi-version=0 --param=min-pagesize=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" -x c++ "$<")
	@echo Building file: $< && arm-none-eabi-g++ @"$@.in"

